kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: video-portal-pv-claim
  labels:
    app: video-portal
spec:
  # storageClassName: fastdata-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-portal
spec:
  replicas: 4
  selector:
    matchLabels:
      app: video-portal
  template:
    metadata:
      labels:
        app: video-portal
    spec:
      containers:
      - name: video-portal
        image: docker.io/mrdojojo/video-portal:v0.9.5
        command: ["/bin/sh", "-c"]
        args:
        - "ls -al && sleep 5 && python3 manage.py makemigrations videoplayer  && sleep 10 && python3 manage.py migrate && sleep 10 && python3 manage.py runserver 0.0.0.0:8000 "
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: code-volume
          mountPath: /media
        - name: kubeconfig
          mountPath: /root/.kube/
          readOnly: true
        env:
          - name: MINIO_ENDPOINT
            value: "console.minio.microk8s.hhii.ampere"
          - name: MINIO_ACCESS_KEY
            value: "4EWGH0OFI6RTHV2YWUCN"
          - name: MINIO_SECRET_KEY
            value: "33bcQW9viP7JKg82OsDCUqaRT6ODuyoTCVRHnAQp"
          - name: MINIO_BUCKET_NAME
            value: "vpp-dst"
          - name: MINIO_SRC_BUCKET_NAME
            value: "vpp-src"
          - name: MINIO_DST_BUCKET_NAME
            value: "vpp-dst"
          - name: VOD_URL
            value: "[URL]"
          - name: DJANGO_ALLOWED_HOSTS
            value: "demo.mk8snode4.hhii.ampere,10.77.123.174,127.0.0.1"
          - name: DB_NAME
            value: "postgres"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_HOST
            value: "10.77.123.174"
          - name: DB_PORT
            value: "30374"

      volumes:
        - name: code-volume
          persistentVolumeClaim:
            claimName: video-portal-pv-claim
        - name: kubeconfig
          configMap:
            defaultMode: 420
            name: kubeconfig-file-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: video-portal-service
spec:
  selector:
    app: video-portal
  type: NodePort
  ports:
    - nodePort: 32080
      protocol: TCP
      port: 8000
      targetPort: 8000

      
---
