apiVersion: v1
kind: Pod
metadata:
  name: vpp-app-db4bea6c-549b-4c10-ae57-a65a1b84c482
  labels:
    app: vpp-app-db4bea6c-549b-4c10-ae57-a65a1b84c482
spec:
  volumes:
  - name: credentials
    configMap:
      name: miniocredentials
  containers:
  - name: vpp-app-db4bea6c-549b-4c10-ae57-a65a1b84c482
    image: docker.io/mrdojojo/video-processor-ffmpeg:1.2
    env:
    - name: ENDPOINT_URL
      value: "http://console.minio.microk8s.hhii.ampere/"
    - name: SRC_OBJECT_KEY
      value: "Ampere_CIDR_1080p.mp4"
    - name: SRC_S3_BUCKET
      value: "vpp-src"
    - name: SRC_S3_REGION
      value: ""
    - name: DST_S3_REGION
      value: ""
    - name: DST_S3_BUCKET
      value: "vpp-dst"
    resources:
      limits:
        cpu: "30"
      requests:
        cpu: "10"
    volumeMounts:
    - name: credentials
      readOnly: true
      mountPath: "/home/altrauser/.aws/credentials"
      subPath: credentials
  restartPolicy: OnFailure
